# Generated by Django 4.2.5 on 2023-09-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_colaboradormodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradormodel',
            name='id_chefe',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='colaboradormodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
