# Generated by Django 4.2.5 on 2023-09-26 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_colaboradormodel_id_chefe_alter_colaboradormodel_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='colaboradormodel',
            table='colaborador',
        ),
    ]
