# Generated by Django 4.2.5 on 2023-09-26 22:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_alter_colaboradormodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradormodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
